# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Adrien ARCURI
email:
privacy_policy_url: privacy-policy
description: >- # this means to ignore newlines until "baseurl:"
  Hello ! I am Adrien software engineer and I.T consultant currently working at <a href='https://klanik.com' target='_blank' rel='noreferrer'>Klanik</a> as project Tech Lead.
baseurl: "" # the subpath of your site, e.g. /blog
url: "adrien.arcuri@github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  adrienarcuri
medium_username: adrienarcuri
linkedin_username: adrienarcuri
youtube_username: UC1xbNhia_Zk6alojX-ecswA
stackoverflow_username: 9418115/adrien-arcuri
codingame_username: e9150912cf02391fc1b7a2a5c3184ada2234602

# Build settings
markdown: kramdown
remote_theme: awochna/jekyll-skeleton
plugins:
  - jekyll-feed

# Sass option
sass:
  style: compressed


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
